// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

/**
 * EnvVar is an optional environment variable injected into ssh child processes.
 */
export interface EnvVar {
    "name": string;
    "value": string;
    "enabled": boolean;
}

/**
 * Forward is a port-forward rule belonging to a tunnel profile.
 */
export interface Forward {
    "id": string;
    "type": ssh$0.TunnelType;
    "localHost": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;
}

/**
 * KnownHostEntry is one non-comment line from a known_hosts file.
 */
export interface KnownHostEntry {
    "index": number;
    "line": string;
    "hosts": string;
    "keyType": string;
    "keyData": string;
}

/**
 * Preferences are app-wide settings (not per-tunnel).
 */
export interface Preferences {
    "showAs": ShowAs;
    "openAtLogin": boolean;
    "authAgent": string;
    "configFile": string;
    "envVars"?: EnvVar[] | null;
}

/**
 * Profile is the GUI unit of configuration: how to reach a host, what to
 * forward, and a few UI preferences. Secrets are never stored here.
 */
export interface Profile {
    "id": string;
    "name": string;
    "hostName": string;
    "user": string;
    "port": number;
    "proxyJump": string;
    "identityFile": string;
    "certificate": string;
    "strictHostKeyChecking": string;
    "hashKnownHosts": boolean;
    "serverAliveInterval": number;
    "serverAliveCountMax": number;

    /**
     * Connection tab
     */
    "logLevel": string;
    "retryAttempts": number;
    "bindAddress": string;

    /**
     * any | inet | inet6
     */
    "addressFamily": string;

    /**
     * -N (recommended)
     */
    "noSession": boolean;
    "compression": boolean;
    "forwardAgent": boolean;

    /**
     * Advanced OpenSSH -o Key=Value overrides (empty value = omit / default).
     */
    "advanced"?: { [_ in string]?: string } | null;
    "forwards": Forward[] | null;
    "notifyOnStatusChange": boolean;
    "autoConnect": boolean;

    /**
     * Pinned tunnels stay at the top of the sidebar list.
     */
    "pinned"?: boolean;
    "tags"?: string[] | null;

    /**
     * DemoStatus / DemoErr are screenshot fixtures only (SWITCHBOARD_DEMO=1).
     * They are never passed to OpenSSH.
     */
    "demoStatus"?: string;
    "demoErr"?: string;
}

/**
 * ShowAs controls whether Switchboard appears in the Dock, menu bar, or both.
 */
export enum ShowAs {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShowAsDock = "dock",
    ShowAsMenuBar = "menubar",
    ShowAsBoth = "both",
};
