// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the Wails-facing API for tunnel configuration and control.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddKnownHost appends a full known_hosts line.
 */
export function AddKnownHost(line: string): $CancellablePromise<void> {
    return $Call.ByID(3728424610, line);
}

/**
 * ClearSavedPassword removes the Keychain password for a tunnel.
 */
export function ClearSavedPassword(id: string): $CancellablePromise<void> {
    return $Call.ByID(590353763, id);
}

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2836621974);
}

/**
 * Connect starts the SSH session for a saved tunnel.
 */
export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(4081416968, id);
}

/**
 * ConnectAll starts every saved tunnel.
 */
export function ConnectAll(): $CancellablePromise<void> {
    return $Call.ByID(3610113483);
}

/**
 * ConnectByTag starts every tunnel that has the given tag.
 */
export function ConnectByTag(tag: string): $CancellablePromise<void> {
    return $Call.ByID(2587593587, tag);
}

/**
 * DeleteTunnel removes a profile and disconnects it.
 */
export function DeleteTunnel(id: string): $CancellablePromise<void> {
    return $Call.ByID(505786535, id);
}

/**
 * Disconnect stops the SSH session.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(4010927372, id);
}

/**
 * DisconnectAll stops every tunnel session.
 */
export function DisconnectAll(): $CancellablePromise<void> {
    return $Call.ByID(2065308631);
}

/**
 * DisconnectByTag stops every tunnel that has the given tag.
 */
export function DisconnectByTag(tag: string): $CancellablePromise<void> {
    return $Call.ByID(3033062095, tag);
}

/**
 * ExportConfiguration writes tunnels + preferences to path (JSON).
 * Keychain passwords/passphrases are never included.
 */
export function ExportConfiguration(path: string): $CancellablePromise<$models.ConfigTransferResult> {
    return $Call.ByID(2725519370, path);
}

/**
 * GetNotificationPermission returns the current notification authorization state.
 */
export function GetNotificationPermission(): $CancellablePromise<$models.NotificationPermission> {
    return $Call.ByID(2614878330);
}

/**
 * GetPreferences returns app-wide settings. OpenAtLogin reflects the live
 * autostart registration when available.
 */
export function GetPreferences(): $CancellablePromise<config$0.Preferences> {
    return $Call.ByID(3633392012);
}

/**
 * GetSSHDefaults returns system defaults for SSH location fields.
 */
export function GetSSHDefaults(): $CancellablePromise<$models.SSHDefaults> {
    return $Call.ByID(2869783182);
}

/**
 * GetTunnel returns one profile + status.
 */
export function GetTunnel(id: string): $CancellablePromise<$models.TunnelView> {
    return $Call.ByID(1847815936, id);
}

/**
 * ImportConfiguration loads tunnels + preferences from path.
 * replace=false merges by profile id; replace=true swaps the full tunnel list.
 * Keychain secrets are never imported. On replace, Keychain items for removed tunnels are deleted.
 */
export function ImportConfiguration(path: string, replace: boolean): $CancellablePromise<$models.ConfigTransferResult> {
    return $Call.ByID(2313656807, path, replace);
}

/**
 * ListKnownHosts returns parsed entries from ~/.ssh/known_hosts.
 */
export function ListKnownHosts(): $CancellablePromise<config$0.KnownHostEntry[] | null> {
    return $Call.ByID(828750828);
}

/**
 * ListTunnels returns every saved profile with live status.
 */
export function ListTunnels(): $CancellablePromise<$models.TunnelView[] | null> {
    return $Call.ByID(1886316137);
}

/**
 * NewTunnelDraft returns a blank profile template (not yet saved).
 */
export function NewTunnelDraft(): $CancellablePromise<config$0.Profile> {
    return $Call.ByID(3913308941);
}

/**
 * OpenMainWindow shows the main Switchboard window.
 */
export function OpenMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(1190527363);
}

/**
 * OpenPathInEditor opens path in the default text editor.
 */
export function OpenPathInEditor(path: string): $CancellablePromise<void> {
    return $Call.ByID(1742694243, path);
}

/**
 * OpenSettings shows the Settings window.
 */
export function OpenSettings(): $CancellablePromise<void> {
    return $Call.ByID(717766711);
}

/**
 * PreviewArgs returns the OpenSSH argument slice for a profile (debug/help).
 */
export function PreviewArgs(p: config$0.Profile): $CancellablePromise<string[] | null> {
    return $Call.ByID(1807475391, p);
}

/**
 * RemoveKnownHost deletes the entry at index from ListKnownHosts.
 */
export function RemoveKnownHost(index: number): $CancellablePromise<void> {
    return $Call.ByID(3292038831, index);
}

/**
 * RequestNotificationPermission prompts macOS for notification access.
 */
export function RequestNotificationPermission(): $CancellablePromise<$models.NotificationPermission> {
    return $Call.ByID(3444220335);
}

/**
 * RevealPathInFinder shows path in Finder (macOS).
 */
export function RevealPathInFinder(path: string): $CancellablePromise<void> {
    return $Call.ByID(4053070587, path);
}

/**
 * SaveTunnel creates or updates a profile and syncs it into the SSH manager.
 * If the tunnel is live and connection settings changed (forwards, host, etc.),
 * the SSH session is restarted so the new args take effect.
 */
export function SaveTunnel(p: config$0.Profile): $CancellablePromise<$models.TunnelView> {
    return $Call.ByID(2519654425, p);
}

/**
 * SendTestNotification delivers a sample notification so permission can be verified.
 */
export function SendTestNotification(): $CancellablePromise<void> {
    return $Call.ByID(776582835);
}

/**
 * SetPassword caches a login password for reconnects and stores it in Keychain.
 */
export function SetPassword(id: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(3203358311, id, password);
}

/**
 * SetPreferences persists settings and applies Show As / Open at Login / SSH runtime.
 */
export function SetPreferences(prefs: config$0.Preferences): $CancellablePromise<config$0.Preferences> {
    return $Call.ByID(1839632472, prefs);
}

/**
 * SetSelection tells the native menu which tunnel is currently selected.
 */
export function SetSelection(id: string): $CancellablePromise<void> {
    return $Call.ByID(711626252, id);
}

/**
 * SubmitPassword answers a PasswordPrompt. Empty secret cancels.
 * When save is true, the secret is written to the macOS Keychain for this tunnel.
 */
export function SubmitPassword(requestID: string, secret: string, save: boolean): $CancellablePromise<void> {
    return $Call.ByID(545811711, requestID, secret, save);
}
