// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "./ssh/models.js";

/**
 * ConfigChangedEvent is emitted after import/export mutates saved tunnels or preferences.
 */
export interface ConfigChangedEvent {
    "reason": string;
}

/**
 * ConfigTransferResult summarizes an export or import.
 */
export interface ConfigTransferResult {
    "path": string;
    "profileCount": number;
    "added"?: number;
    "updated"?: number;
    "removed"?: number;
    "message": string;
}

/**
 * NotificationPermission describes macOS notification authorization state.
 */
export interface NotificationPermission {
    "authorized": boolean;
    "available": boolean;
    "message": string;
}

/**
 * PasswordPrompt is emitted when OpenSSH needs a secret.
 */
export interface PasswordPrompt {
    "requestId": string;
    "hostId": string;
    "prompt": string;
    "kind": string;
}

/**
 * SSHDefaults are resolved default paths shown when overrides are empty.
 */
export interface SSHDefaults {
    "authAgent": string;
    "configFile": string;
    "knownHosts": string;
}

/**
 * StatusEvent is emitted whenever a tunnel's connection state changes.
 */
export interface StatusEvent {
    "hostId": string;
    "snap": ssh$0.Snapshot;
}

/**
 * TunnelView is a profile plus live status for the UI.
 */
export interface TunnelView {
    "profile": config$0.Profile;
    "status": ssh$0.Snapshot;
}
