version: '3'

vars:
  APP_NAME: "Switchboard"
  BIN_DIR: "bin"
  PACKAGE_MANAGER: '{{.PACKAGE_MANAGER | default "npm"}}'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

includes:
  common: ./build/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml

tasks:
  build:
    summary: Builds the macOS application
    cmds:
      - task: darwin:build

  package:
    summary: Packages Switchboard.app
    cmds:
      - task: darwin:package

  run:
    summary: Runs the application
    cmds:
      - task: darwin:run

  dmg:
    summary: Packages a styled .dmg
    cmds:
      - task: darwin:package:dmg

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
