// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot is a point-in-time view of a managed SSH process.
 */
export interface Snapshot {
    "Status": Status;
    "Err": string;
    "PID": number;
    "Logs": string;
}

/**
 * Status is the connection state of a host session.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusDisconnected = "disconnected",
    StatusConnecting = "connecting",
    StatusConnected = "connected",
    StatusError = "error",
};

/**
 * TunnelType is an OpenSSH forwarding mode.
 */
export enum TunnelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TunnelLocal = "local",
    TunnelRemote = "remote",
    TunnelDynamic = "dynamic",
    TunnelReverseDynamic = "reverse-dynamic",
};
